---
permalink: /guides/guide-codewind/
---
:layout: guide
:duration: 30
:description: Take advantage of Codewind's tools to help build high quality cloud native applications regardless of which IDE or language you use.
:tags: ['kabanero', 'appsody', 'codewind', 'microservice']
:projectid: guide-codewind
:page-layout: guide
:page-duration: 30
:page-releasedate: TBD
:page-guide-category: developer tools
:page-essential: true
:page-essential-order: 1
:page-description: Take advantage of Codewind's tools to help build high quality cloud native applications regardless of which IDE or language you use. 
:guide-author: Kabanero
:page-tags: ['kabanero', 'appsody', 'codewind', 'microservice']
:page-permalink: /guides/{projectid}
:repo-description: TBD
= Getting Started with Codewind in Kabanero
:toc:

[ATTN]: opening PR for review of guide

== Objectives

*Learning objectives*

You can either:

* Install Codewind and begin <<#developing-with-vs-code, developing with VS Code>> or <<#developing-with-eclipse, developing with Eclipse>>. 
* Develop a simple microservice with your chosen IDE. 

== Kabanero Overview 

Before working with Codewind, understand that Codewind works within Kabanero, an open source project in a microservices-based framework.
For more information on how Kabanero and its components work, visist https://kabanero.io/guides/overview/#architecture[Kabanero's Architecture and Development Workflows].

To deploy your applications onto OpenShift, you need to build and work with Kabanero Collections. If you plan to deploy any applications onto OpenShift complete the guide, https://kabanero.io/guides/working-with-collections/[Working with Kabanero Collections]. 

== Developing a simple microservice

=== *Developing with VS Code*

Why Visual Studio Code (VS Code)? You can use Codewind for VS Code to develop and debug your containerized projects from within VS Code.

Codewind for VS Code supports development of Microprofile/Java EE, Java Lagom, Spring, Node.js, Go,Python, Swift, and Appsody containerized projects.

*Prerequisite*

Before you can develop a microservice with VS Code, you need to:

* https://docs.docker.com/install/[Install Docker] 
** [Note]: Make sure to install or upgrade to minimum Docker version 19.03. 
* https://code.visualstudio.com/download[Install VS Code]
 
*Installing Codewind for VS Code*

The Codewind installation includes two parts:

. The VS Code extension installs when you install Codewind from the https://marketplace.visualstudio.com/items?itemName=IBM.codewind[VS Code Marketplace] and click `Install`. 
* Or, go to `View->Extensions`, search for Codewind, and click `Install`. 
. The Codewind backend containers install after you click `Install` when you are prompted. After you click `Install`, the necessary images are downloaded from the internet. The download is approximately 1 GB.
* [Optional]: If you don’t click `Install` when the notification window first appears, you can access the notification again. Go to `View->Explorer`. Then click `Codewind` and hover the cursor over `Codewind` where there is a switch to turn Codewind on or off. Click the switch so that it is `On`. The notification window is displayed. 

The following images are pulled. These images together form the Codewind backend:
```
. eclipse/codewind-performance-amd64 
. eclipse/codewind-pfe-amd64
```

*Creating an Appsody project*

Appsody helps you develop containerized applications and removes the burden of managing the full software development stack. If you want more context about Appsody, visit the https://appsody.dev/docs[Appsody welcome page]. 

. Under the Explorer pane, select `Codewind`.
. Expand `Codewind` by clicking the drop-down arrow. 
. Hover over the `Projects` entry underneath Codewind in the Explorer pane, and press the `+` icon to create a project.
* [Note]: Make sure Docker is running. Otherwise, you get an error. 
. Choose the `Appsody Eclipse MicroProfile template`. 
. Name your project `appsody-calculator`.
* If you don't see Appsody templates, find and select `Template Source Manager` and enable `Appsody Stacks - appsodyhub`. 
* The templates are refreshed, and the Appsody templates are available. 
. Press `Enter`. 
* To monitor your project's progress, right-click your project, and select `Show all logs`. Then an `Output` tab is displayed where you see your project's build logs. 

Your project is complete when you see your application status is running and your build status is successful. 

*Accessing the application endpoint in a browser*

. Return to your project under the Explorer pane. 
. Select the Open App icon next to your project's name, or right-click your project and select `Open App`. 

Your application is now opened in the browser, showing the welcome to your Appsody microservice page.

*Adding a REST service to your application*

 . Go to your project's workspace under the Explorer tab. 
 . Navigate to `src->main->java->dev->appsody->starter`.
 . Right-click `starter` and select `New File`.
 . Create a file, name it `Calculator.java`, and press `Enter`. This file is your JAX-RS resource. 
 . Populate the file with the following code.
 . Save the file after you input the code. 

```
package dev.appsody.starter;

import javax.ws.rs.core.Application;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import javax.ws.rs.PathParam;

@Path("/calculator")
public class Calculator extends Application {

    @GET
    @Path("/aboutme")
    @Produces(MediaType.TEXT_PLAIN)
    public String aboutme(){
        return "You can add (+), subtract (-), and multiply (*) with this simple calculator.";
    }

    @GET
    @Path("/{op}/{a}/{b}")
    @Produces(MediaType.TEXT_PLAIN)
    public Response calculate(@PathParam("op") String op, @PathParam("a") String a, @PathParam("b") String b)
    {
        int numA = Integer.parseInt(a);
        int numB = Integer.parseInt(b);

      switch(op)
      {
          case "+":
              return Response.ok(a + "+" + b + "=" + (Integer.toString((numA + numB)))).build();

          case "-":
              return Response.ok(a + "-" + b + "=" + (Integer.toString((numA - numB)))).build();

          case "*":
              return Response.ok(a + "*" + b + "=" + (Integer.toString((numA * numB)))).build();

          default:
              return Response.ok("Invalid operation. Please Try again").build();
      }
    }
}
```
Any changes you make to your code will automatically be built and re-deployed by Codewind and viewed in your browser. 

*Working with the microservice* 

You now can work with your calculator.

. Use the port number you saw when you first opened the application.
. Make sure to remove the `< >` symbol in the URL. 
. `http://127.0.0.1:<port>/starter/calculator/aboutme` 
. You should see the following response:

```
You can add (+), subtract (-), and multiply (*) with this simple calculator.
```

You could also try a few of the sample calculator functions: 

* `http://127.0.0.1:<port>/starter/calculator/{op}/{a}/{b}`, where you can input one of the available operations `(+, _, *)`, and an integer a, and an integer b.
* So for `http://127.0.0.1:<port>/starter/calculator/+/10/3` you should see: `10+3=13`.

*Nice work! Where to next?*

You have created a simple microservice using the VS Code IDE. For further learning:

* Visit this https://www.eclipse.org/codewind/mdt-vsc-tutorial.html[tutorial on Codewind for VS Code].
* Review https://www.eclipse.org/codewind/mdt-vsc-commands-project.html[project commands for Codewind for VS Code].

=== *Developing with Eclipse*

Why Eclipse? You can use Codewind for Eclipse to develop and debug your containerized projects from within Eclipse.

Codewind for Eclipse supports development of Microprofile/Java EE, Java Lagom, Spring, Node.js, Go,Python, Swift, and Appsody containerized projects. 

*Prerequisite* 

Before you can develop a microservice with Eclipse, you need to:

* https://docs.docker.com/install/[Install Docker] 
** [Note]: Make sure to install or upgrade to minimum Docker version 19.03. 
* https://www.eclipse.org/downloads/packages/release/[Install Eclipse]
** [Note]: Make sure to install or upgrade to mimimum Eclipse version 2019-09 R (4.13.0). 

*Installing Codewind for Eclipse*

The Codewind installation includes two parts:

.  The Eclipse plug-in installs when you install Codewind from the https://marketplace.eclipse.org/content/codewind[Eclipse Marketplace] or when you install by searching in the `Eclipse Extensions` view.
. The Codewind backend containers install after you click `Install`. After you click `Install`, the necessary images are downloaded from the internet. The download is approximately 1 GB.

The following images are pulled. These images together form the Codewind backend:
```
. eclipse/codewind-performance-amd64
. eclipse/codewind-pfe-amd64
```

*Creating an Appsody project*

Appsody helps you develop containerized applications and removes the burden of managing the full software development stack. If you want more context about Appsody, visit the https://appsody.dev/docs[Appsody welcome page]. 

. Click the `Codewind` tab.
. Expand `Codewind` by clicking the drop-down arrow.
. Right-click `Projects (Local)`.
. Select `Create New Project...`
* [Note]: Make sure Docker is running. Otherwise, you get an error. 
. Name your project `appsody-calculator`. 
. Under `Template`, select `Appsody Eclipse MicroProfile template`. 
* If you don't see an Appsody template, select the `Manage Template Sources...` link at the end of the window.
* Select the `Appsody Stacks - appsodyhub` checkbox. 
* Click `OK`.
* The templates are refreshed, and the Appsody templates are available. 
. Click `Finish`.
* To monitor your project's progress, right-click on your project, and select `Show Log Files`.
* Select `Show All`. Then a `Console` tab is displayed where you see your project's build logs. 

Your project is displayed in the `Projects (Local)` section. The progress for creating your project is tracked next to the project's name. 

Your project is complete when you see your project is running and its build is successful. 

*Accessing the application endpoint in a browser*

. Return to your project under the Codewind tab. 
. Right-click your project and select `Open Application`. 

Your application is now opened in the browser, showing the welcome to your Appsody microservice page. 

*Adding a REST service to your application*

. Go to your project's workspace under the Project Explorer tab. 
. Navigate to `Java Resources->src/main/java->dev.appsody.starter`. 
. Right-click `dev.appsody.starter` and select `New->Class`.
. Create a Class file, name it `Calculator.java`, and select `Finish`. This file is your JAX-RS resource. 
. Populate the file with the following code. 
. Save the file after you input the code. 

```
package dev.appsody.starter;

import javax.ws.rs.core.Application;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import javax.ws.rs.PathParam;

@Path("/calculator")
public class Calculator extends Application {

    @GET
    @Path("/aboutme")
    @Produces(MediaType.TEXT_PLAIN)
    public String aboutme(){
        return "You can add (+), subtract (-), and multiply (*) with this simple calculator.";
    }

    @GET
    @Path("/{op}/{a}/{b}")
    @Produces(MediaType.TEXT_PLAIN)
    public Response calculate(@PathParam("op") String op, @PathParam("a") String a, @PathParam("b") String b)
    {
        int numA = Integer.parseInt(a);
        int numB = Integer.parseInt(b);

      switch(op)
      {
          case "+":
              return Response.ok(a + "+" + b + "=" + (Integer.toString((numA + numB)))).build();

          case "-":
              return Response.ok(a + "-" + b + "=" + (Integer.toString((numA - numB)))).build();

          case "*":
              return Response.ok(a + "*" + b + "=" + (Integer.toString((numA * numB)))).build();

          default:
              return Response.ok("Invalid operation. Please Try again").build();
      }
    }
}
```
Any changes you make to your code will automatically be built and re-deployed by Codewind and viewed in your browser.

*Working with the microservice* 

You now can work with your calculator. 

* Use the port number you saw when you first opened the application.
* Make sure to remove the `< >` symbol in the URL. 
* http://127.0.0.1:<port>/starter/calculator/aboutme 
* You should see the following response:

```
You can add (+), subtract (-), and multiply (*) with this simple calculator.
```

You could also try a few of the sample calculator functions:

* `http://127.0.0.1:<port>/starter/calculator/{op}/{a}/{b}`, where you can input one of the available operations `(+, _, *)`, and an integer a, and an integer b.
* So for `http://127.0.0.1:<port>/starter/calculator/+/10/3` you should see: `10+3=13` 

*Nice work! Where to next?*

You have completed a simple microservice using the Eclipse IDE. For further learning: 

* Review https://www.eclipse.org/codewind/mdteclipsemanagingprojects.html[managing Codewind projects for Eclipse]. 

== What you have learned 

Now that you have completed this guide, you have:

. Installed Codewind on your preference of VS Code or Eclipse.
. Developed your own microservice using Codewind.
