---
permalink: /guides/app-monitoring/
---
:projectid: guide-codewind
:page-layout: guide-multipane
:page-duration: TBD
:page-releasedate: TBD
:page-guide-category: monitoring
:page-essential: true
:page-essential-order: 1
:page-description: To install Codewind on Eclipse and create a simple app with Eclipse. 
:page-tags: ['kabanero', 'appsody', 'codewind', 'tekton']
:page-permalink: /guides/{projectid}
:repo-description: TBD
= Developing a simple app with Eclipse 

*Table of contents*

1. Why Eclipse? +
2. Install Codewind for Eclipse +
3. Use Appsody template +
4. Create project +
5. Edit project files +
6. Test new endpoint +
7. Debug app +
8. Run app +
9. Nice work and where to next

*1. Why Eclipse?*

You can use Codewind for Eclipse to develop and debug your containerized projects from within Eclipse.

Use the Eclipse IDE to create and make modifications to your application, see the application and build status, view the logs, and run your application.
Codewind for Eclipse supports development of Microprofile/Java EE, Java Lagom, Spring, Node.js, Go, Python, Swift, and Appsody containerized projects. 
In addition, Microprofile/Java EE, Spring, and Node.js applications can be debugged.

The Eclipse tools are open source. You are encouraged to browse the code, open issues, and contribute.

*2. Install Codewind for Eclipse*

The Codewind installation includes two parts:

1. The Eclipse plug-in installs when you install Codewind from the Eclipse Marketplace or when you install by searching in the *Eclipse Extensions* view. +
2. The Codewind back end containers install after you click *Install* when you are prompted. After you click *Install*, the necessary images are downloaded from the internet. The download is approximately 1 GB. +
3. Optional: If you don’t click *Install* when the notification window first appears, you can access the notification again. Go to the Explorer view, hover the cursor over *Codewind*, and click the switch so that it changes to the *On* position. The window appears.

The following images are pulled. These images together form the Codewind back end:

1. eclipse/codewind-initialize-amd64 +
2. eclipse/codewind-performance-amd64 +
3. eclipse/codewind-pfe-amd64

When the installation is complete, the extension is ready to use, and you are prompted to open the Codewind workspace. 

Codewind creates the `~/codewind-workspace` folder to contain your projects.
On Windows, you can find the workspace at the `C:\codewind-workspace` folder. 
You can open the `codewind-workspace` or a project within the workspace as your Eclipse workspace. 

*3. Use Appsody template*

Instructions here on how to retrieve and use Appsody’s templates. 

*4. Create project*

Note: users will work with the Java application that comes with the Eclipse installation.

You can work with your Codewind projects from the *Codewind Explorer* view in Eclipse.
If the view is not showing, open it as follows:

1. From the *Window* menu select *Show View > Other.* +
2. Start to type *Codewind* in the filter field or locate and expand the *Codewind* entry in the list. +
3. Select *Codewind Explorer* and click *Open.*

To create a new project or import an existing one, use the context menu on the *Local Projects* item in the *Codewind Explorer* view. 
Once you have a project, the first thing you might want to do is import your project into the Eclipse workspace so you can start editing files.
This also makes your source available for debugging.

Each project shows the application status and the build status. 
A context menu on each project enables you to open your application in a browser, view application and build logs, restart in debug mode, and much more.

When auto build is enabled for a project, Codewind for Eclipse detects when you make a change and starts a build automatically.
If you have disabled auto build for the project, you can start a build manually when you have made a change or a set of changes:

1. Right-click your project in the *Codewind Explorer* view and select *Build.* +
2. Wait for the project state to return to *Running* or *Debugging* in the *Codewind Explorer* view and then test your changes.

*5. Edit project files*

Editing actions are available by right clicking on the project in the *Codewind Explorer* view.
Most actions are only available if the project is enabled.

Some actions open the default Eclipse browser. 
If you find that the default Eclipse browser cannot handle the content, change the default browser by navigating to *Window > Web Browser* and selecting a different browser from the list.

Project settings tell Codewind more about the specifics of your project and can affect the status and/or behavior of your application. 
You can configure project settings when you:

1. Go to Project Overview page that is accessible from a project’s context menu, or, + 
2. Find the project settings in the *.cw-settings* file of the project which you can edit

*6. Test new endpoint*

Instructions here on how to test the new endpoint

*7. Debug app*

Codewind for Eclipse supports debugging Microprofile/Java EE and Spring projects.
The tools also help you set up a debug session for Node.js projects in a Chromium based browser.

Debugging Microprofile/Java EE and Spring projects:

Prerequisites:

1. If you have not done so already, import your project into Eclipse to make the source available to debug. +
    * Right-click your project in the *Codewind Explorer* view. +
    * Select *Import Project.* +
2. If you need to debug any initialization code, set breakpoints in this code now. You can also set breakpoints in your application code at this time. +
3. [Optional] If you want to use Java hot code replace and change your code while you debug, disable automatic builds. +
    * To disable automatic builds, right-click your project in the *Codewind Explorer* view and select *Disable Auto Build.* +
    * If you want to start a build while automatic builds are disabled, right-click your project and select *Build.* +
    * Enable automatic builds again after you finish debugging. To enable automatic builds again, right-click your project and select *Enable Auto Build.*

Debugging:

 1. To restart your Microprofile/Java EE or Spring application in debug mode, right-click on the project in the *Codewind Explorer* view and select *Restart in Debug Mode.* +
 2. If you did not import your project into Eclipse you are prompted to do so now. Select one of the following: +
    * *Yes:* To import your project into Eclipse and make the source available for debugging. +
    * *No:* To continue restarting in debug mode without importing your project. There might be no source available for debugging if you choose this option. +
    * *Cancel:* To cancel restarting your application in debug mode. +
 3. Wait for the project state to change to *Debugging* or for the debugger to stop at a breakpoint if you are debugging initialization code. If you have hit a breakpoint in initialization code, skip to step 6. +
 4. If you have not done so already, set up any breakpoints that you need in your application. +
 5. Reload your application in the browser or, if you have not already opened it, right-click on the project in the *Codewind Explorer* view and select *Open Application.* +
 6. Eclipse prompts you to switch to the *Debug* perspective when a breakpoint is hit or you can switch manually by clicking *Window > Perspective > Open Perspective > Debug.* All of the Java debug capabilities provided by Eclipse including various breakpoint types, the *Variables* and *Expression* views, and hot code replace are available to you. +
 7. You can reload your application multiple times to isolate the problem. However, if you are debugging initialization code, you must restart your project in debug mode to stop in this code again. +
 8. When you have finished debugging, you can switch back to run mode. Right-click on your project in the *Codewind Explorer* view and select *Restart in Run Mode.*
 
Attaching to a project in debug mode: 
 
If you detached from the debugger, or you restarted Eclipse, you can attach the debugger without restarting again:
 
 1. Make sure to do any of the setup you need such as importing your project into Eclipse and setting breakpoints. For more information, see Prerequisites. +
 2. Right click on your project in the *Codewind Explorer* view and select *Attach Debugger.* The *Attach Debugger* menu item is only available for Codewind/Java EE or Spring applications in debug mode if a debugger is not already attached.
 
Debugging Node.js projects:

You can restart your Node.js application in debug mode and the tools help you launch a debug session in a Chromium based web browser:

1. To restart your Node.js application in debug mode, right-click on the project in the *Codewind Explorer* view and select *Restart in Debug Mode.* +
2. If you are prompted to select a Chromium based web browser for launching the debug session: +
	* Select a Chromium based browser from the list of browsers or use the *Manage* link to add one. +
	* Optionally, select to always use this browser for Node.js debugging. +
	* Click *OK* to continue. +
3. Launch a debug session using the information on the *Node.js Debug Inspector URL* dialog: +
	* Click the *Copy URL to Clipboard* button to copy the debug URL. +
	* Click the *Open Browser* button to open the browser you selected in the previous dialog. +
	* Paste the URL into the address bar of the browser to start the debug session.

Launching a debug session for a Node.js project in debug mode: 

You can launch a debug session for a Node.js project that is already in debug mode.

1. Right-click on your project in the *Codewind Explorer* view and select *Launch Debug Session.* This menu item is only available for Node.js projects in debug mode if a debug session is not already started. +
2. Follow the steps in Debugging Node.js projects to launch a Node.js debug session, starting with step 2. 

Modifying the Node.js debug launch preferences: 

To change the browser to use when launching a Node.js debug session, edit the Codewind preferences:

1. Open the Eclipse preferences and select *Codewind* from the list. +
2. In the *Select a Chromium based web browser for launching the Node.js debugger* group, choose a Chromium based web browser from the list of browsers or add one using the *Manage*link. You can also clear the selected browser by selecting *No web browser selected* in the list. +
3. Click *Apply and Close.*

*8. Run Application* 

Instructions here on how to run the application. 

*9. Nice Work and Where to Next*

If you would like to use Codewind with Eclipse Che or VS Code, you may read instructions to install and work with those IDEs in this guide. 

To continue to learn about Codewind, visit Codewind API, https://eclipse.github.io/codewind/. 
